### ISSUE TITLE
Extension -> Site web

### ISSUE THREAD

**Issue by FazCodeFR** [xfournet/sdp-remote-control#1]
Salut, très beau travail gg ! 
Je voudrais savoir comment transformé le code source de ton extension en projet local pour pouvoir ensuite l'héberger sur mon site (je sais pas si tu me comprends, en gros ne plus passer par une extension mais directement par un site web) 

J'aimerais mettre ton extension sur mon site , et le top serais de pouvoir y faire des requête get avec les bouton et ips ^^

Si tu pourrais m'aider ça serrais super ! Je suis nouveau dans le dev web ^^

Merci encore

**Comment by xfournet** [comment]
Un example a été rajouté dans le répertoire HTML. Cependant suivant le navigateur utilisé il ne marchera que si la page est servi via une connection HTTP et non HTTPS car la WebSocket n'est pas sécurisé (à ma connaissance ce n'est pas possible avec ce décodeur). Par exemple https://raw.githack.com/xfournet/sdp-remote-control/master/html/remote.html ne va pas fonctionner avec Chrome

**Comment by ABOATDev** [comment]
Merci a toi ! 
Il marche bien sur mon site http://fazcode.com/test/remote.html même avec Chrome

Maintenant je vais essayé de le transformé en php pour transmettre les données
http://fazcode.com/test/remote.php?ip=192.168.1.X&chaine=25

Mais je n'est jamais fais du php et c’est le seul moyen que je trouve pour contrôlé mon décodeur à distance ^^ Si tu a un peu de temps pour m'aider ^^

Merci énormément sinon tu m'a bien avancer avec la version HTML
